name: download

on: workflow_dispatch
jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
  
    - name: Install packages
      run: |
        source tools/ci.sh && ci_esp32_idf44_setup
        
    - name: Build
      run: |
        make ${MAKEOPTS} -C mpy-cross
        make ${MAKEOPTS} -C ports/esp32 submodules
        make ${MAKEOPTS} -C ports/esp32 BOARD=GENERIC_C3

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: c3-release
        path: ~/esp/micropython/ports/esp32/build*/firmware.bin